### ISSUE TITLE
Question about the dataset

### ISSUE THREAD

**Issue by LinghaoChan** [blackgold3/SemanticBoost#1]
Hi, @blackgold3 

Thanks for your work! Will you release the augmented text data and codes for augmentation? Furthermore, I have another question. Is the augmentation mainly about the motion trajectory?

**Comment by blackgold3** [comment]
We try to augment the textual descriptions of motion trajectory, head orientation, and the position of the left forearm (which is the middle point of the left wrist and left elbow.)  But motion trajectory may be more obvious for demos. 

As for codes for augmentation, we will release them as soon as possible, but the exact time has not been decided yet.

**Comment by LinghaoChan** [comment]
Thank you for the quick reply. Is the right forearm available?

**Comment by blackgold3** [comment]
Not yet. In fact, previous work such as T2M-GPT and MDM augment the motion data by flipping left and right. I think the left forearm and right forearm are the same. We can augment the right forearm information according to similar rules or even flip the left forearm and corresponding descriptions directly.

**Comment by LinghaoChan** [comment]
thx🤝
