### ISSUE TITLE
About  args.rep == "smr"

### ISSUE THREAD

**Issue by CDLCHOI** [blackgold3/SemanticBoost#3]
In the function get_model_args()， 
if args.rep == "smr", then njoints += 6。

I know that the motion data dim of HumanML3D is 263, 
but what is the "smr", and why  njoints += 6.

**Comment by blackgold3** [comment]
Smr is a little different representation that replaces the [67 to 67+21x6] dimensions of HumanML3D representation by SMPL rotation information (22 x 6). Therefore, the total dimensions are 269.

**Comment by CDLCHOI** [comment]
1. Does smr come from any paper? I haven't heard that. 
   Could you tell me some details about it? 

2. The original slice  [67: 67 + 21x6] means the 6D rotation of 21 non-root joints with respect to its parent node.
    I'm wondering the meaning of 22x6 rotation?  
    Can you explain that? 

Thank you!

**Comment by blackgold3** [comment]
1. I do not know if other paper utilizes similar representation. For more details, you can refer the paper of this repo.

**Comment by blackgold3** [comment]
1. I do not know if there is any other paper that uses a similar representation. For more details, you can refer to https://arxiv.org/abs/2310.20323
2. Both of them are 6D rotation information. The process of exporting HumanML3D representation is: SMPL rotation -> 3D joints -> HumanML3D, so 21 x 6 is derived from the position of 3D joints. 22 x 6 includes the root joint which may not be necessary. The process of exporting SMR representation is: SMPL rotation -> 3D joints + SMPL rotation -> SMR.

**Comment by CDLCHOI** [comment]
Thanks for your reply !
